//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Market_System
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MarketDBEntities : DbContext
    {
        public MarketDBEntities()
            : base("name=MarketDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<BidModel> BidModels { get; set; }
        public DbSet<BucketModel> BucketModels { get; set; }
        public DbSet<CartModel> CartModels { get; set; }
        public DbSet<CommentModel> CommentModels { get; set; }
        public DbSet<ContractModel> ContractModels { get; set; }
        public DbSet<EmployeeModel> EmployeeModels { get; set; }
        public DbSet<LotteryModel> LotteryModels { get; set; }
        public DbSet<MessageModel> MessageModels { get; set; }
        public DbSet<ProductAttributeModel> ProductAttributeModels { get; set; }
        public DbSet<ProductModel> ProductModels { get; set; }
        public DbSet<PurchasePolicyModel> PurchasePolicyModels { get; set; }
        public DbSet<PurchaseStrategyModel> PurchaseStrategyModels { get; set; }
        public DbSet<StoreModel> StoreModels { get; set; }
        public DbSet<StorePurchaseHistoryObjModel> StorePurchaseHistoryObjModels { get; set; }
        public DbSet<TimerModel> TimerModels { get; set; }
        public DbSet<TransactionModel> TransactionModels { get; set; }
        public DbSet<UserModel> UserModels { get; set; }
        public DbSet<UserPurchaseHistoryObjModel> UserPurchaseHistoryObjModels { get; set; }
    }
}
